### ISSUE TITLE
Delete marks of a student in a course. Get marks of a certain course of a student.

### ISSUE THREAD

**Issue by muhammadammar33** [muhammadammar33/LMS#17]
**2 Routes**

Delete marks of a student in a course. _(/teacher/deletemarks/:sid/:cid)_
Get marks of all courses of a student. _(student/getmarks/:sid)_

**Comment by TheProProgrammer** [comment]
tera

**Comment by TheProProgrammer** [comment]
Issue modified due to feature being already implemented.

**Comment by TheProProgrammer** [comment]
Sent branch as a pull request.
