### ISSUE TITLE
View teacher profile. Retrieve list of students in classes taught by the teacher. Retrieve list of classes enrolled by the student.

### ISSUE THREAD

**Issue by muhammadammar33** [muhammadammar33/LMS#21]
**3 Routes**

- View teacher profile.  _(/teacher/profile/:tid)_
- Retrieve list of students in classes taught by the teacher. _(/teacher/students/:tid)_
- Retrieve list of classes enrolled by the student. _(/student/classes/:sid)_

**Comment by muhammadsaadgondal** [comment]
hamesha der kr det hun
