### ISSUE TITLE
Retrieve list of grades for the student. Retrieve list of teachers for classes enrolled by the student. Update details of a specific course.

### ISSUE THREAD

**Issue by muhammadammar33** [muhammadammar33/LMS#23]
**3 Routes**

- Retrieve list of grades for the student. _(/student/grades/:sid)_
- Retrieve list of teachers for classes enrolled by the student. _(/student/teachers/:sid)_
- Update details of a specific course. _(/courses/updatecourse/:cid)_

**Comment by hammadsaedi** [comment]
Hey. I think, `PUT` or `PATCH` request to `/courses/:cid` would be understood as an update operation.

**Comment by hammadsaedi** [comment]
Yoo. 
```
Retrieve list of grades for the student. (/student/grades/:sid)
```
It's bit confusing, There is no grade mentioned in schema. 
@muhammadammar33
