### ISSUE TITLE
Unenroll a student from a specific course. Retrieve details of a specific teacher.

### ISSUE THREAD

**Issue by muhammadammar33** [muhammadammar33/LMS#24]
**2 Routes**

- Unenroll a student from a specific course. _(/courses/:cid/unenroll-student/:sid)_
- Retrieve details of a specific teacher. _(/student/teachers//:sid/:tid)_

**Comment by ranasamiulhaq** [comment]
[Task.zip](https://github.com/muhammadammar33/LMS/files/15366156/Task.zip)

The 2 Routes are uploaded
