### ISSUE TITLE
Get list of classes enrolled by the student. Get details of a specific class enrolled by the student. Get list of teachers of classes enrolled by the student.

### ISSUE THREAD

**Issue by muhammadammar33** [muhammadammar33/LMS#6]
**3 Routes**

- Get list of classes enrolled by the student. _(/student/classes)_
- Get details of a specific class enrolled by the student. _(/student/classes/:id)_
- Get list of teachers of classes enrolled by the student. _(/student/teachers)_

**Comment by hammadsaedi** [comment]
@aliabbas217 jaldi sy issue resolve kro, phr ap ny ML b krni hy.
